### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by a0bie** [ay-lab/mustache#3]
Thank you for putting out this cool tool! In your pre-print it was mentioned that:

> 5kb resolution ... we employed Mustache using two octaves with default parameters (σ<sub>0</sub> = 1.6 and s = 10)

But no explicit statement was made about the parameters applied to 10kb resolution data. Could you please share if you used the same ones? Also, several parameters were said to be 'experimentally chosen for 5Kb resolution', would it be possible to learn some more detail about the process to potentially replicate the results?

**Comment by ay-lab** [comment]
Hi a0bie, thanks for using our tool. Same parameters have been used for 10kb resolution which means q-val threshold 0.05, σ0 = 1.6, s = 10, st=0.88, octaves=2. All experiments were conducted on the text format input of the datasets so that we can do the preliminary sparsity checking (not to be confused with the final sparsity test -st 0.88). You can see that filtering in the 'read_bias' function: "if val<0.2:  d[(float(line[1]) // res)] = np.Inf". Let me know if I  have missed anything.

**Comment by a0bie** [comment]
I see! Thank you for the clarification
