### ISSUE TITLE
Large loops

### ISSUE THREAD

**Issue by meisterpeter** [ay-lab/mustache#31]
Hi,
I love mustache, it is very good at detecting loops. I have an issue with large loops. The detection limit is set to 4Mb, whereas I can see in my HiC map (2kb resolution) a number of loops which are larger than this. Is there a way to avoid the 4Mb size limit (let's say to put it to chromosome size)? Thanks for your answer! Peter

**Comment by ay-lab** [comment]
Hi Peter, thank you for using our tool and sorry for the delay. The reason that we limit the distance is that detecting more distant loops comes with the price of missing some other loops. But you can hardcode the distance you want by uncommenting  and changing the line#1048 (#distFilter = 4000000). However, I wouldn't change it to a very large number for 2kb resolution since it is going to need a lot of memory. Let me know how it goes.
